[source.crates-io]
replace-with = 'rsproxy-sparse'

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

# static 推荐在项目中配置
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# static 推荐在项目中配置
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
